# Generated by Django 4.2.1 on 2023-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_request_remove_channelmessage_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.CharField(default='Do you want to create new chat?', max_length=255),
        ),
    ]
